# Generated by Django 5.2 on 2025-04-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_occurred_on', models.DateTimeField(blank=True, null=True)),
                ('alarm_cleared_on', models.DateTimeField(blank=True, null=True)),
                ('alarm_source', models.CharField(max_length=255)),
                ('alarm_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('site_parsed_alarm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JoinedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_occurred_on', models.DateTimeField(blank=True, null=True)),
                ('alarm_cleared_on', models.DateTimeField(blank=True, null=True)),
                ('alarm_source', models.CharField(max_length=255)),
                ('alarm_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('site_parsed_alarm', models.CharField(max_length=100)),
                ('outage_occurred_on', models.DateTimeField(blank=True, null=True)),
                ('outage_cleared_on', models.DateTimeField(blank=True, null=True)),
                ('mo_name', models.CharField(max_length=255)),
                ('outage_name', models.CharField(max_length=255)),
                ('site_parsed_outage', models.CharField(max_length=100)),
                ('battery_backup_time', models.CharField(blank=True, max_length=100)),
                ('backup_minutes', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outage_occurred_on', models.DateTimeField(blank=True, null=True)),
                ('outage_cleared_on', models.DateTimeField(blank=True, null=True)),
                ('mo_name', models.CharField(max_length=255)),
                ('outage_name', models.CharField(max_length=255)),
                ('site_parsed_outage', models.CharField(max_length=100)),
            ],
        ),
    ]
